-- MySQL Script generated by MySQL Workbench
-- Wed Mar 25 12:34:14 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `CategoryID` INT NOT NULL AUTO_INCREMENT,
  `CategorName` VARCHAR(45) NOT NULL,
  `Description` TEXT(1000) NULL,
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Products` (
  `ProductID` INT NOT NULL AUTO_INCREMENT,
  `Category_CategoryID` INT NOT NULL,
  `ProductName` VARCHAR(45) NOT NULL,
  `ProductDescription` TEXT(1000) NOT NULL,
  `Quantity` INT NOT NULL,
  `Price` INT NOT NULL,
  `PromoCode` VARCHAR(5) NULL,
  `StockLevel` INT NOT NULL,
  PRIMARY KEY (`ProductID`),
  INDEX `fk_Products_Category_idx` (`Category_CategoryID` ASC),
  CONSTRAINT `fk_Products_Category`
    FOREIGN KEY (`Category_CategoryID`)
    REFERENCES `mydb`.`Category` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrderDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrderDetails` (
  `OrderID` VARCHAR(45) NOT NULL,
  `Quantity` INT NOT NULL,
  `Price` INT NOT NULL,
  `Products_ProductID` INT NOT NULL,
  `Order` VARCHAR(45) NULL,
  INDEX `fk_OrderDetails_Products1_idx` (`Products_ProductID` ASC),
  PRIMARY KEY (`OrderID`),
  CONSTRAINT `fk_OrderDetails_Products1`
    FOREIGN KEY (`Products_ProductID`)
    REFERENCES `mydb`.`Products` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `StaffName` VARCHAR(45) NOT NULL,
  `AdminName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `EmployeeID` INT NOT NULL AUTO_INCREMENT,
  `User_UserID` INT NOT NULL,
  `Department` VARCHAR(45) NOT NULL,
  `ContractHours` INT NOT NULL,
  INDEX `fk_Employee_User1_idx` (`User_UserID` ASC),
  PRIMARY KEY (`EmployeeID`),
  CONSTRAINT `fk_Employee_User1`
    FOREIGN KEY (`User_UserID`)
    REFERENCES `mydb`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Addresses` (
  `AddressID` INT NOT NULL AUTO_INCREMENT,
  `HouseNo` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `PostCode` VARCHAR(7) NOT NULL,
  `PhoneNo` INT NOT NULL,
  `User_UserID` INT NOT NULL,
  PRIMARY KEY (`AddressID`, `HouseNo`),
  INDEX `fk_Address_User1_idx` (`User_UserID` ASC),
  CONSTRAINT `fk_Address_User1`
    FOREIGN KEY (`User_UserID`)
    REFERENCES `mydb`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customers` (
  `CustomersID` INT NOT NULL AUTO_INCREMENT,
  `FIrstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `CustomerInfo` TEXT(1000) NOT NULL,
  `PhoneNo` INT NOT NULL,
  `Addresses_AddressID` INT NOT NULL,
  `Addresses_HouseNo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CustomersID`),
  INDEX `fk_Customers_Addresses1_idx` (`Addresses_AddressID` ASC, `Addresses_HouseNo` ASC),
  CONSTRAINT `fk_Customers_Addresses1`
    FOREIGN KEY (`Addresses_AddressID` , `Addresses_HouseNo`)
    REFERENCES `mydb`.`Addresses` (`AddressID` , `HouseNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `OrderID` INT NOT NULL AUTO_INCREMENT,
  `OrderNumber` VARCHAR(45) NOT NULL,
  `OrderDate` DATETIME NOT NULL,
  `ShippingDate` DATETIME NOT NULL,
  `Orderscol` VARCHAR(45) NULL,
  `Employee_EmployeeID` INT NOT NULL,
  `Customers_CustomersID` INT NOT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `fk_Orders_Employee1_idx` (`Employee_EmployeeID` ASC),
  INDEX `fk_Orders_Customers1_idx` (`Customers_CustomersID` ASC),
  CONSTRAINT `fk_Orders_Employee1`
    FOREIGN KEY (`Employee_EmployeeID`)
    REFERENCES `mydb`.`Employee` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Customers1`
    FOREIGN KEY (`Customers_CustomersID`)
    REFERENCES `mydb`.`Customers` (`CustomersID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Company/Supp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Company/Supp` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Delivery/Shipping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Delivery/Shipping` (
  `Orders_OrderID` INT NOT NULL,
  `DeliveryID` INT NOT NULL AUTO_INCREMENT,
  `CompanyName` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(45) NOT NULL,
  `OrderDetails_OrderID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DeliveryID`),
  INDEX `fk_Delivery/Shipping_OrderDetails1_idx` (`OrderDetails_OrderID` ASC),
  CONSTRAINT `fk_Delivery/Shipping_Orders1`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Orders` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Delivery/Shipping_OrderDetails1`
    FOREIGN KEY (`OrderDetails_OrderID`)
    REFERENCES `mydb`.`OrderDetails` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Complaints`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Complaints` (
  `ComplaintsID` INT NULL AUTO_INCREMENT,
  `ComplaintMessage` TEXT(1000) NULL,
  `Complaintscol` VARCHAR(45) NULL,
  `Customers_CustomersID` INT NOT NULL,
  PRIMARY KEY (`ComplaintsID`),
  INDEX `fk_Complaints_Customers1_idx` (`Customers_CustomersID` ASC),
  CONSTRAINT `fk_Complaints_Customers1`
    FOREIGN KEY (`Customers_CustomersID`)
    REFERENCES `mydb`.`Customers` (`CustomersID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
